"use client"

import "./globals.css"
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import { ThemeProvider } from "@/Context/ThemeContext";
import { Provider} from "react-redux";
import store from "@/redux/store";
import { LineWave } from "react-loader-spinner";
import SetUser from "./Components/Authentication/SetUser";
import CustomizedSnackbars from "./Components/Authentication/CustomizedSnackbars";
import SetWatchlist from "./Components/Authentication/SetWatchlist";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <body>
        <ThemeProvider>
          <Provider store={store}>
            <SetUser />
            <SetWatchlist />
            <Navbar />
            {children}
            {/* <Footer /> */}
            <CustomizedSnackbars />
          </Provider>
        </ThemeProvider>
      </body>
    </html>

  );
}
