"use client"

import "./globals.css"
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import { ThemeProvider } from "@/Context/ThemeContext";
import { Provider } from "react-redux";
import store from "@/redux/store";
import { useEffect, useState } from "react";
import { LineWave } from "react-loader-spinner";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <body>
        <ThemeProvider>
          <Provider store={store}>
            <Navbar />
            {children}
            {/* <Footer /> */}
          </Provider>
        </ThemeProvider>
      </body>
    </html>

  );
}
